version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: SimpleTodoApp/Dockerfile.backend
    ports:
      - "5162:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - todo-network

  frontend:
    build:
      context: .
      dockerfile: SimpleTodoApp/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge